{% set name = "django-configurations" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-configurations-{{ version }}.tar.gz
  sha256: 6e5083757e2bbdf9bb7850567536b96a93515f6b17503d74928ff628db2e0e94

build:
  noarch: python
  entry_points:
    - django-cadmin = configurations.management:execute_from_command_line
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools-scm
    - pip
  run:
    - python >=3.8,<4.0
    - django >=3.2

test:
  imports:
    - configurations
  commands:
    - pip check
    - DJANGO_CONFIGURATION=core.settings DJANGO_SETTINGS_MODULE=django django-cadmin --help
  requires:
    - pip

about:
  home: https://django-configurations.readthedocs.io/
  summary: A helper for organizing Django settings.
  dev_url: https://github.com/jazzband/django-configurations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - millsks
    - rxm7706
