{% set name = "django-configurations" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-configurations-{{ version }}.tar.gz
  sha256: bd1a77a60735839b7d105912cc3977735fa005ea06544c632fbd322d1e021677

build:
  number: 0
  noarch: python
  entry_points:
    - django-cadmin = configurations.management:execute_from_command_line
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - six
    - django >=1.8

test:
  imports:
    - configurations
  # needs to fix a dep in django
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://django-configurations.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A helper for organizing Django project settings by relying on well established programming patterns.  '
  description: |
    django-configurations eases Django project configuration by relying on the composability of Python classes. It extends the notion of Django's module based settings loading with well established object oriented programming patterns.
  doc_url: https://django-configurations.readthedocs.io/en/latest/
  dev_url: https://github.com/jazzband/django-configurations

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
